# Numpy arrays:

<p>NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.
reference: click <a href=https://numpy.org/devdocs/user/absolute_beginners.html target="_blank" rel="noreferrer noopener">here</a>

#### To use numpy array:

In [1]:
import numpy as np

#### To create an array of 0s with shape (3, 4) :

In [2]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### To create an array of 1s with shape (2, 3, 4) :

In [3]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### To create an array of evenly spaced values (step value) :

In [4]:
np.arange(10, 25, 5)

array([10, 15, 20])

#### To create a 2x2 identity matrix :

In [5]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

#### To create an array of evenly spaced values (number of samples) :

In [6]:
# 9 elements(samples) from 0 to 2
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### To create an array :

In [7]:
a = np.array([1, 2, 3])

b = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype=np.float64) # we used dtype to convert the ints to floats

c = np.array([[[1.5, 2, 3],
               [4, 5, 6]],
              [[3, 2, 1], 
               [4, 5, 6]]], dtype=np.float64)

#### Array dimensions :

In [8]:
print("array a : " + str(a.shape))
print("array b : " + str(b.shape))
print("array c : " + str(c.shape))

array a : (3,)
array b : (2, 3)
array c : (2, 2, 3)


#### The datatype of array elements :

In [9]:
print('the elements of a are :', a.dtype)
print('the elements of a are :', b.dtype)
print('the elements of a are :', c.dtype)

the elements of a are : int32
the elements of a are : float64
the elements of a are : float64


#### we can use indexing as in lists :

In [10]:
# to access the third element of the array a:
a[2]

3

In [11]:
# to select the element at row 1 column 2:
b[1, 2]

6.0

In [12]:
# to select items at index 0 and 1:
a[0:2]

array([1, 2])

In [13]:
#select items at rows 0 and 1 in column 1:
b[0:2, 1]

array([2., 5.])

#### To transpose an array :

In [14]:
print(b)
print("\n")
print("The transpose of b is : \n", str(np.transpose(b)))

[[1. 2. 3.]
 [4. 5. 6.]]


The transpose of b is : 
 [[1. 4.]
 [2. 5.]
 [3. 6.]]


In [15]:
# or we can use:
print(b)
print("\n")
print("The transpose of b is : \n", str(b.T))

[[1. 2. 3.]
 [4. 5. 6.]]


The transpose of b is : 
 [[1. 4.]
 [2. 5.]
 [3. 6.]]


#### To flatten an array (transform it to 1D array) :

In [16]:
print("Array b :\n", b)
print("\n")
print("The flattened b :\n", b.ravel())

Array b :
 [[1. 2. 3.]
 [4. 5. 6.]]


The flattened b :
 [1. 2. 3. 4. 5. 6.]


#### To create a numpy array from lists :

In [17]:
py_list = [1, 2, 3, 4]
py_array = np.array(py_list)
print(py_array)
print('\n')
print(type(py_array))

[1 2 3 4]


<class 'numpy.ndarray'>


#### We can use operations on these arrays :

In [18]:
print("array a : ", a)
print("array a + 1 :", a+1)

array a :  [1 2 3]
array a + 1 : [2 3 4]


In [19]:
print("array a² :", a**2)

array a² : [1 4 9]


In [20]:
# or we can use lambda functions
square = lambda x : x**2
print(square(a))

[1 4 9]


In [21]:
a + a**2

array([ 2,  6, 12])

In [22]:
a+b

array([[2., 4., 6.],
       [5., 7., 9.]])

In [23]:
a / b

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [24]:
a * b

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [25]:
a - b

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [26]:
d = [1, 2, 3, 4]
e = [1, 2, 3, 4]
g = [1, 2, 3, 5]

In [27]:
d == e

True

In [28]:
d == g

False

In [29]:
#or we can use:
np.array_equal(d, e)

True

In [30]:
# to reshape an array:
print("array b :\n", b)
print("\n")
print("array b reshaped to 3 rows and 2 columns :\n", b.reshape(3, 2))

array b :
 [[1. 2. 3.]
 [4. 5. 6.]]


array b reshaped to 3 rows and 2 columns :
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [31]:
# to compute the sum of an array elements:
print(b)
print("\n")
print(b.sum())

[[1. 2. 3.]
 [4. 5. 6.]]


21.0
